assets:
    js:
        app:
            - jquery-1.11.3.min.js
            - bootstrap.min.js
            - app.js
        admin:
            - jquery-1.11.3.min.js
            - bootstrap.min.js
            - admin.js
