AppBundle\Entity\User:
    properties:
        lastName:
            - NotNull:
                message: form.user.last_name.not_null
        firstName:
            - NotNull:
                message: form.user.first_name.not_null
        birthdayDate:
            - Date:
                message: form.user.birthday_date.date
    getters:
        lower:
            - IsTrue:
                message: form.user.birthday_date.lower

AppBundle\Entity\EventType:
    properties:
        name:
            - NotNull:
                message: form.event_type.name.not_null

AppBundle\Entity\Event:
    properties:
        name:
            - NotNull:
                message: form.event.name.not_null
        location:
            - NotNull:
                message: form.event.location.not_null
        date:
            - DateTime:
                message: form.event.date.datetime

AppBundle\Entity\TicketCategory:
    properties:
        label:
            - NotNull:
                message: form.ticket_category.label.not_null

AppBundle\Entity\Stock:
    properties:
        quantity:
            - Type:
                type: integer
                message: form.stock.quantity.int
