AppBundle\Entity\User:
    properties:
        lastName:
            - not_null:
                message: form.user.last_name.not_null
        firstName:
            - not_null:
                message: form.user.first_name.not_null
AppBundle\Entity\EventType:
    properties:
        name:
            - NotNull:
                message: form.event_type.name.not_null
